export const ancData = [
    {
        "id": 1,
        "subCentre": "Chilpur(SC)",
        "ancId": "P140200261472516",
        "ancName": "Biyya swathi",
        "ancContactNo": "8519800585",
        "lmp": "1-Jan-2025",
        "edd": "08/10/2025",
        "ancWo": "Mahesh",
        "village": "Chilpur",
        "ancAge": 21,
        "gravida": "G2",
        "previousDeliveryMode": "Govt-Normal",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "24-Sep-2025",
        "addressOfDeliveredAborted": "Jangoan MCH",
        "modeOfDeliveryAborted": "Govt-Normal",
        "ashaName": "U Renuka",
        "ashaContactNo": "9502674132",
        "status": "ongoing"
    },
    {
        "id": 2,
        "subCentre": "Chilpur(SC)",
        "ancId": "P140200261135626",
        "ancName": "Murahari bhavana",
        "ancContactNo": "9440936089",
        "lmp": "13-Jan-2025",
        "edd": "20/10/2025",
        "ancWo": "Vishal",
        "village": "Chilpur",
        "ancAge": 27,
        "gravida": "G2",
        "previousDeliveryMode": "Govt-Normal",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "20-Oct-2025",
        "addressOfDeliveredAborted": "HNK GMH",
        "modeOfDeliveryAborted": "OtherGovt-Normal",
        "ashaName": "U Renuka",
        "ashaContactNo": "9502674132",
        "status": "ongoing"
    },
    {
        "id": 3,
        "subCentre": "Chilpur(SC)",
        "ancId": "P140200261341797",
        "ancName": "Mallam Susmitha",
        "ancContactNo": "7207462170",
        "lmp": "29-Dec-2024",
        "edd": "05/10/2025",
        "ancWo": "Ranjith kumar",
        "village": "Chilpur",
        "ancAge": 22,
        "gravida": "G2",
        "previousDeliveryMode": "Pvt-LSCS",
        "causeOfHighRisk": "",
        "birthPlan": "MCH Jangaon",
        "dateOfDeliveryAborted": "2-Oct-2025",
        "addressOfDeliveredAborted": "Dharmasagar pvt ,Bhavana hospital",
        "modeOfDeliveryAborted": "Pvt-LSCS",
        "ashaName": "P Bujatha",
        "ashaContactNo": "9121338631",
        "status": "ongoing"
    },
    {
        "id": 4,
        "subCentre": "Chinnapendyal(SC)",
        "ancId": "P14020028346462",
        "ancName": "THALLAPALLY MANISHA",
        "ancContactNo": "8978273743",
        "lmp": "8-Jan-2025",
        "edd": "15/10/2025",
        "ancWo": "Harish",
        "village": "chinnapendyal",
        "ancAge": 25,
        "gravida": "G2",
        "previousDeliveryMode": "Govt-LSCS",
        "causeOfHighRisk": "Lscs",
        "birthPlan": "MCH Jangaon",
        "dateOfDeliveryAborted": "1-Oct-2025",
        "addressOfDeliveredAborted": "Gmh",
        "modeOfDeliveryAborted": "Pvt-LSCS",
        "ashaName": "Blalitha",
        "ashaContactNo": "9912714546",
        "status": "ongoing"
    },
    {
        "id": 5,
        "subCentre": "Chinnapendyal(SC)",
        "ancId": "P140200281375634",
        "ancName": "Royyala Ravali",
        "ancContactNo": "9666108826",
        "lmp": "10-Jan-2025",
        "edd": "17/10/2025",
        "ancWo": "Raju",
        "village": "chinnapendyal",
        "ancAge": 24,
        "gravida": "G2",
        "previousDeliveryMode": "Govt-LSCS",
        "causeOfHighRisk": "",
        "birthPlan": "MCH Jangaon",
        "dateOfDeliveryAborted": "30-Jul-2025",
        "addressOfDeliveredAborted": "Abarion",
        "modeOfDeliveryAborted": "",
        "ashaName": "ch Sukanya",
        "ashaContactNo": "7036115006",
        "status": "ongoing"
    },
    {
        "id": 6,
        "subCentre": "Chinnapendyal(SC)",
        "ancId": "P140200282052091",
        "ancName": "Ellandula swathi",
        "ancContactNo": "9963277479",
        "lmp": "17-Jan-2025",
        "edd": "24/10/2025",
        "ancWo": "kanakaiah",
        "village": "chinnapendyal",
        "ancAge": 26,
        "gravida": "G2",
        "previousDeliveryMode": "Govt-LSCS",
        "causeOfHighRisk": "Lscs",
        "birthPlan": "MCH Jangaon",
        "dateOfDeliveryAborted": "8-Oct-2025",
        "addressOfDeliveredAborted": "Gmh",
        "modeOfDeliveryAborted": "Govt-LSCS",
        "ashaName": "E Rani",
        "ashaContactNo": "9177807793",
        "status": "ongoing"
    },
    {
        "id": 7,
        "subCentre": "Chinnapendyal(SC)",
        "ancId": "P140200281943519",
        "ancName": "Suvarnna",
        "ancContactNo": "8897316903",
        "lmp": "17-Jan-2025",
        "edd": "24/10/2025",
        "ancWo": "Rajashekar",
        "village": "chinnapendyal",
        "ancAge": 25,
        "gravida": "G2",
        "previousDeliveryMode": "Govt-LSCS",
        "causeOfHighRisk": "Lscs",
        "birthPlan": "MCH Jangaon",
        "dateOfDeliveryAborted": "25-Oct-2025",
        "addressOfDeliveredAborted": "Gmh",
        "modeOfDeliveryAborted": "Govt-LSCS",
        "ashaName": "E Rani",
        "ashaContactNo": "9177807793",
        "status": "ongoing"
    },
    {
        "id": 8,
        "subCentre": "Kistajigudem (SC)",
        "ancId": "P140200321275565",
        "ancName": "Banoth vinodha",
        "ancContactNo": "6302829752",
        "lmp": "27-Dec-2024",
        "edd": "03/10/2025",
        "ancWo": "Venkatesh",
        "village": "Fathepur",
        "ancAge": 20,
        "gravida": "G2",
        "previousDeliveryMode": "Pvt-LSCS",
        "causeOfHighRisk": "Lscs",
        "birthPlan": "MCH Jangaon",
        "dateOfDeliveryAborted": "17-Oct-2025",
        "addressOfDeliveredAborted": "GMH.Hnk",
        "modeOfDeliveryAborted": "Govt-LSCS",
        "ashaName": "P Elisha",
        "ashaContactNo": "9989171392",
        "status": "ongoing"
    },
    {
        "id": 9,
        "subCentre": "Kistajigudem (SC)",
        "ancId": "P140200321497053",
        "ancName": "Lakshmidevi",
        "ancContactNo": "7671873448",
        "lmp": "6-Jan-2025",
        "edd": "13/10/2025",
        "ancWo": "Vijay",
        "village": "Fathepur",
        "ancAge": 20,
        "gravida": "G2",
        "previousDeliveryMode": "Pvt-LSCS",
        "causeOfHighRisk": "Lscs",
        "birthPlan": "MCH Jangaon",
        "dateOfDeliveryAborted": "17-Sep-2025",
        "addressOfDeliveredAborted": "pvt sujatha hospital HNK",
        "modeOfDeliveryAborted": "Pvt-LSCS",
        "ashaName": "M. Ramadevi",
        "ashaContactNo": "9391753928",
        "status": "ongoing"
    },
    {
        "id": 10,
        "subCentre": "Malkapur(SC)",
        "ancId": "P140200241177120",
        "ancName": "Racha akshara",
        "ancContactNo": "9347452998",
        "lmp": "19-Jan-2025",
        "edd": "26/10/2025",
        "ancWo": "Rajukumar",
        "village": "Malkapur",
        "ancAge": 25,
        "gravida": "G2",
        "previousDeliveryMode": "OtherGovt-LSCS",
        "causeOfHighRisk": "Lscs",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "23-Oct-2025",
        "addressOfDeliveredAborted": "Siddiet Govt Hospital",
        "modeOfDeliveryAborted": "Govt-Normal",
        "ashaName": "Ch.Rajitha",
        "ashaContactNo": "7207067727",
        "status": "ongoing"
    },
    {
        "id": 11,
        "subCentre": "Nashkal(SC)",
        "ancId": "P140200291426376",
        "ancName": "Sushmitha",
        "ancContactNo": "9381880783",
        "lmp": "22-Jan-2025",
        "edd": "29/10/2025",
        "ancWo": "Madhu",
        "village": "Nashkal",
        "ancAge": 26,
        "gravida": "G2",
        "previousDeliveryMode": "Govt-LSCS",
        "causeOfHighRisk": "",
        "birthPlan": "MCH Jangaon",
        "dateOfDeliveryAborted": "14-Oct-2025",
        "addressOfDeliveredAborted": "Ckm warangal",
        "modeOfDeliveryAborted": "Govt-Normal",
        "ashaName": "A Fathima",
        "ashaContactNo": "9133654095",
        "status": "ongoing"
    },
    {
        "id": 12,
        "subCentre": "Pallagutta(SC)",
        "ancId": "P140200311503692",
        "ancName": "Aparna",
        "ancContactNo": "9581315742",
        "lmp": "24-Jan-2025",
        "edd": "31/10/2025",
        "ancWo": "Sampath",
        "village": "Pallagutta",
        "ancAge": 29,
        "gravida": "G2",
        "previousDeliveryMode": "Govt-LSCS",
        "causeOfHighRisk": "Lscs",
        "birthPlan": "MCH Jangaon",
        "dateOfDeliveryAborted": "27-Sep-2025",
        "addressOfDeliveredAborted": "Private",
        "modeOfDeliveryAborted": "Pvt-LSCS",
        "ashaName": "K.Venkat laxmi",
        "ashaContactNo": "8978192724",
        "status": "ongoing"
    },
    {
        "id": 13,
        "subCentre": "Pallagutta(SC)",
        "ancId": "P140200301389169",
        "ancName": "Bhukya Swetha",
        "ancContactNo": "9110518591",
        "lmp": "20-Jan-2025",
        "edd": "27/10/2025",
        "ancWo": "Venu",
        "village": "Deshaithanda",
        "ancAge": 23,
        "gravida": "G2",
        "previousDeliveryMode": "Govt-LSCS",
        "causeOfHighRisk": "Lscs",
        "birthPlan": "MCH Jangaon",
        "dateOfDeliveryAborted": "17-Oct-2025",
        "addressOfDeliveredAborted": "Mch Jangaon",
        "modeOfDeliveryAborted": "Govt-LSCS",
        "ashaName": "B.Neela",
        "ashaContactNo": "8790336439",
        "status": "ongoing"
    },
    {
        "id": 14,
        "subCentre": "Pallagutta(SC)",
        "ancId": "P200101901148317",
        "ancName": "Ravalika",
        "ancContactNo": "9121578994",
        "lmp": "28-Dec-2024",
        "edd": "04/10/2025",
        "ancWo": "Raju",
        "village": "Pallagutta",
        "ancAge": 25,
        "gravida": "G2",
        "previousDeliveryMode": "Govt-LSCS",
        "causeOfHighRisk": "Lscs",
        "birthPlan": "MCH Jangaon",
        "dateOfDeliveryAborted": "12-Sep-2025",
        "addressOfDeliveredAborted": "Mch Jangaon",
        "modeOfDeliveryAborted": "Govt-LSCS",
        "ashaName": "K.Venkat laxmi",
        "ashaContactNo": "8978192724",
        "status": "ongoing"
    },
    {
        "id": 15,
        "subCentre": "Rajavaram(SC)",
        "ancId": "P050201171434080",
        "ancName": "Dasarapu Akhila",
        "ancContactNo": "8978893508",
        "lmp": "28-Dec-2024",
        "edd": "04/10/2025",
        "ancWo": "Ranjith",
        "village": "Rajavaram",
        "ancAge": 24,
        "gravida": "G2",
        "previousDeliveryMode": "Govt-Normal",
        "causeOfHighRisk": "-",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "25-Sep-2025",
        "addressOfDeliveredAborted": "GMH HNK",
        "modeOfDeliveryAborted": "OtherGovt-Normal",
        "ashaName": "A Padma",
        "ashaContactNo": "8106569127",
        "status": "ongoing"
    },
    {
        "id": 16,
        "subCentre": "Rajavaram(SC)",
        "ancId": "P14010078850366",
        "ancName": "Naraboina Manasa",
        "ancContactNo": "9908987986",
        "lmp": "15-Jan-2025",
        "edd": "22/10/2025",
        "ancWo": "Ramesh",
        "village": "Rajavaram",
        "ancAge": 22,
        "gravida": "G2",
        "previousDeliveryMode": "Govt-LSCS",
        "causeOfHighRisk": "LSCS",
        "birthPlan": "MCH Jangaon",
        "dateOfDeliveryAborted": "25-Sep-2025",
        "addressOfDeliveredAborted": "Malla Reddy HYD",
        "modeOfDeliveryAborted": "Pvt-LSCS",
        "ashaName": "A Vijaya",
        "ashaContactNo": "7330773781",
        "status": "ongoing"
    },
    {
        "id": 17,
        "subCentre": "Rajavaram(SC)",
        "ancId": "P140200271619556",
        "ancName": "E Maheshwari",
        "ancContactNo": "9493785648",
        "lmp": "26-Dec-2024",
        "edd": "02/10/2025",
        "ancWo": "Yakub",
        "village": "Fakeer thanda",
        "ancAge": 21,
        "gravida": "G2",
        "previousDeliveryMode": "Govt-LSCS",
        "causeOfHighRisk": "LSCS",
        "birthPlan": "MCH Jangaon",
        "dateOfDeliveryAborted": "3-Oct-2025",
        "addressOfDeliveredAborted": "GMH HNK",
        "modeOfDeliveryAborted": "Govt-LSCS",
        "ashaName": "G Neelima",
        "ashaContactNo": "9701696383",
        "status": "ongoing"
    },
    {
        "id": 18,
        "subCentre": "Sripathipally(SC)",
        "ancId": "P290100461578565",
        "ancName": "Gouthami",
        "ancContactNo": "8897343655",
        "lmp": "14-Jan-2025",
        "edd": "21/10/2025",
        "ancWo": "Narendar",
        "village": "Lingampally",
        "ancAge": 25,
        "gravida": "G2",
        "previousDeliveryMode": "Govt-LSCS",
        "causeOfHighRisk": "Lacs",
        "birthPlan": "MCH Jangaon",
        "dateOfDeliveryAborted": "12-Oct-2025",
        "addressOfDeliveredAborted": "Govt Kadupa",
        "modeOfDeliveryAborted": "OtherGovt-LSCS",
        "ashaName": "Suma",
        "ashaContactNo": "7036208138",
        "status": "ongoing"
    },
    {
        "id": 19,
        "subCentre": "Sripathipally(SC)",
        "ancId": "P140200251459929",
        "ancName": "BATHINI BHARGAVI",
        "ancContactNo": "9704963620",
        "lmp": "21-Jan-2025",
        "edd": "28/10/2025",
        "ancWo": "Sandeep",
        "village": "Lingampally",
        "ancAge": 26,
        "gravida": "G2",
        "previousDeliveryMode": "Pvt-LSCS",
        "causeOfHighRisk": "Lscs",
        "birthPlan": "MCH Jangaon",
        "dateOfDeliveryAborted": "3-Oct-2025",
        "addressOfDeliveredAborted": "pvt hyd",
        "modeOfDeliveryAborted": "OtherGovt-LSCS",
        "ashaName": "Suma",
        "ashaContactNo": "7036208138",
        "status": "ongoing"
    },
    {
        "id": 20,
        "subCentre": "Chilpur(SC)",
        "ancId": "14020026000026",
        "ancName": "Thokala Sangeetha",
        "ancContactNo": "9167641032",
        "lmp": "2-Jan-2025",
        "edd": "09/10/2025",
        "ancWo": "Raju",
        "village": "Venkatadripeta",
        "ancAge": 29,
        "gravida": "G3",
        "previousDeliveryMode": "Govt-Normal",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "14-Oct-2025",
        "addressOfDeliveredAborted": "Hnk Gmh",
        "modeOfDeliveryAborted": "Govt-Normal",
        "ashaName": "K Laxmi",
        "ashaContactNo": "8897818962",
        "status": "ongoing"
    },
    {
        "id": 21,
        "subCentre": "Kistajigudem (SC)",
        "ancId": "P14020025711147",
        "ancName": "Sadam sandya",
        "ancContactNo": "6281027663",
        "lmp": "29-Dec-2024",
        "edd": "05/10/2025",
        "ancWo": "Sandeep",
        "village": "Krishnajigudem",
        "ancAge": 22,
        "gravida": "G3",
        "previousDeliveryMode": "Govt-LSCS",
        "causeOfHighRisk": "Lscs",
        "birthPlan": "MCH Jangaon",
        "dateOfDeliveryAborted": "4-Oct-2025",
        "addressOfDeliveredAborted": "pvt.devika.hospital.Hnk",
        "modeOfDeliveryAborted": "Pvt-LSCS",
        "ashaName": "M.sudha",
        "ashaContactNo": "6300112940",
        "status": "ongoing"
    },
    {
        "id": 22,
        "subCentre": "Kistajigudem (SC)",
        "ancId": "P14020043149667",
        "ancName": "Belli mamatha",
        "ancContactNo": "9515611132",
        "lmp": "12-Jan-2025",
        "edd": "19/10/2025",
        "ancWo": "sambaraju",
        "village": "krishnajigudem",
        "ancAge": 27,
        "gravida": "G3",
        "previousDeliveryMode": "Pvt-LSCS",
        "causeOfHighRisk": "Lscs",
        "birthPlan": "MCH Jangaon",
        "dateOfDeliveryAborted": "25-Sep-2025",
        "addressOfDeliveredAborted": "Govt tamilnadu",
        "modeOfDeliveryAborted": "Govt-LSCS",
        "ashaName": "E.Renuka",
        "ashaContactNo": "7993595296",
        "status": "ongoing"
    },
    {
        "id": 23,
        "subCentre": "Malkapur(SC)",
        "ancId": "P14020024145730",
        "ancName": "Karalli Ravali",
        "ancContactNo": "9949353048",
        "lmp": "14-Jan-2025",
        "edd": "21/10/2025",
        "ancWo": "Kumara swami",
        "village": "Malkapur",
        "ancAge": 26,
        "gravida": "G3",
        "previousDeliveryMode": "Govt-LSCS",
        "causeOfHighRisk": "LSCS",
        "birthPlan": "MCH Jangaon",
        "dateOfDeliveryAborted": "10-Oct-2025",
        "addressOfDeliveredAborted": "GMH HNK",
        "modeOfDeliveryAborted": "Govt-LSCS",
        "ashaName": "T.Rajitha",
        "ashaContactNo": "",
        "status": "ongoing"
    },
    {
        "id": 24,
        "subCentre": "Malkapur(SC)",
        "ancId": "P14020024208850",
        "ancName": "Bandi Rama",
        "ancContactNo": "9398205528",
        "lmp": "14-Jan-2025",
        "edd": "21/10/2025",
        "ancWo": "Ramesh",
        "village": "Malkapur",
        "ancAge": 26,
        "gravida": "G3",
        "previousDeliveryMode": "Govt-LSCS",
        "causeOfHighRisk": "Lscs",
        "birthPlan": "MCH Jangaon",
        "dateOfDeliveryAborted": "3-Jun-2025",
        "addressOfDeliveredAborted": "Adhya hospital",
        "modeOfDeliveryAborted": "Aborted",
        "ashaName": "B.Rajitha",
        "ashaContactNo": "99896558170",
        "status": "aborted"
    },
    {
        "id": 25,
        "subCentre": "Chilpur(SC)",
        "ancId": "P140200261401870",
        "ancName": "Uppula Harshitha",
        "ancContactNo": "7993451897",
        "lmp": "16-Jan-2025",
        "edd": "23/10/2025",
        "ancWo": "Sai Sagar",
        "village": "Venkatadripeta",
        "ancAge": 25,
        "gravida": "G4",
        "previousDeliveryMode": "",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "30-May-2025",
        "addressOfDeliveredAborted": "HNK GMH",
        "modeOfDeliveryAborted": "Aborted",
        "ashaName": "K. Anitha",
        "ashaContactNo": "9618364513",
        "status": "aborted"
    },
    {
        "id": 26,
        "subCentre": "Chilpur(SC)",
        "ancId": "P140200262029322",
        "ancName": "Jakkam Ramya",
        "ancContactNo": "8179465450",
        "lmp": "1-Jan-2025",
        "edd": "08/10/2025",
        "ancWo": "Srujan",
        "village": "Chilpur",
        "ancAge": 21,
        "gravida": "Primi",
        "previousDeliveryMode": "",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "9-Oct-2025",
        "addressOfDeliveredAborted": "HNK Pvt ,Lavanya hospital",
        "modeOfDeliveryAborted": "Pvt-LSCS",
        "ashaName": "U Renuka",
        "ashaContactNo": "9502674132",
        "status": "ongoing"
    },
    {
        "id": 27,
        "subCentre": "Chilpur(SC)",
        "ancId": "P140200262062917",
        "ancName": "Thimmapuram Divya",
        "ancContactNo": "9542488122",
        "lmp": "15-Jan-2025",
        "edd": "22/10/2025",
        "ancWo": "Hemanth",
        "village": "Chilpur",
        "ancAge": 25,
        "gravida": "Primi",
        "previousDeliveryMode": "",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "11-Oct-2025",
        "addressOfDeliveredAborted": "HNK GMH",
        "modeOfDeliveryAborted": "OtherGovt-Normal",
        "ashaName": "B Balamani",
        "ashaContactNo": "7095382616",
        "status": "ongoing"
    },
    {
        "id": 28,
        "subCentre": "Chilpur(SC)",
        "ancId": "P140200262036153",
        "ancName": "Gandu Vennela",
        "ancContactNo": "9347744257",
        "lmp": "5-Jan-2025",
        "edd": "12/10/2025",
        "ancWo": "Karnakar",
        "village": "Venkatadripeta",
        "ancAge": 19,
        "gravida": "Primi",
        "previousDeliveryMode": "",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "17-May-2025",
        "addressOfDeliveredAborted": "Hnk Gmh",
        "modeOfDeliveryAborted": "Aborted",
        "ashaName": "K. Laxmi",
        "ashaContactNo": "8897818962",
        "status": "aborted"
    },
    {
        "id": 29,
        "subCentre": "Kistajigudem (SC)",
        "ancId": "P140200322046621",
        "ancName": "Atram pochubai",
        "ancContactNo": "8668351147",
        "lmp": "21-Jan-2025",
        "edd": "28/10/2025",
        "ancWo": "Santhosh",
        "village": "krishnajigudem",
        "ancAge": "20G2",
        "gravida": "Primi",
        "previousDeliveryMode": "",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "20-Oct-2025",
        "addressOfDeliveredAborted": "GMH.Hnk",
        "modeOfDeliveryAborted": "Govt-LSCS",
        "ashaName": "E.Renuka",
        "ashaContactNo": "7993595296",
        "status": "ongoing"
    },
    {
        "id": 30,
        "subCentre": "Kistajigudem (SC)",
        "ancId": "P140200322068504",
        "ancName": "Banoth Narmada",
        "ancContactNo": "9963302759",
        "lmp": "26-Dec-2024",
        "edd": "02/10/2025",
        "ancWo": "Rajender",
        "village": "fathepur",
        "ancAge": 23,
        "gravida": "Primi",
        "previousDeliveryMode": "",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "21-Oct-2025",
        "addressOfDeliveredAborted": "GMH.Hnk",
        "modeOfDeliveryAborted": "Govt-LSCS",
        "ashaName": "M.Ramadevi",
        "ashaContactNo": "9391753928",
        "status": "ongoing"
    },
    {
        "id": 31,
        "subCentre": "Kistajigudem (SC)",
        "ancId": "P140200322066060",
        "ancName": "Ganda Anitha",
        "ancContactNo": "6304481750",
        "lmp": "19-Jan-2025",
        "edd": "26/10/2025",
        "ancWo": "shailender reddy",
        "village": "Krishnajigudem",
        "ancAge": 31,
        "gravida": "Primi",
        "previousDeliveryMode": "",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "21-Oct-2025",
        "addressOfDeliveredAborted": "Mch jangaon",
        "modeOfDeliveryAborted": "Govt-LSCS",
        "ashaName": "E sandhya",
        "ashaContactNo": "7207470180",
        "status": "ongoing"
    },
    {
        "id": 32,
        "subCentre": "Malkapur(SC)",
        "ancId": "P140200242026368",
        "ancName": "Shivrathi Shirisha",
        "ancContactNo": "7095580554",
        "lmp": "29-Dec-2024",
        "edd": "05/10/2025",
        "ancWo": "Anvesh",
        "village": "kondapur",
        "ancAge": 23,
        "gravida": "Primi",
        "previousDeliveryMode": "",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "24-Sep-2025",
        "addressOfDeliveredAborted": "MCH Jangaon",
        "modeOfDeliveryAborted": "Govt-Normal",
        "ashaName": "M.Vijayarani",
        "ashaContactNo": "8009976804",
        "status": "ongoing"
    },
    {
        "id": 33,
        "subCentre": "Malkapur(SC)",
        "ancId": "P140200242035403",
        "ancName": "alugu akhila",
        "ancContactNo": "9177157783",
        "lmp": "27-Dec-2024",
        "edd": "03/10/2025",
        "ancWo": "Raj Kumar",
        "village": "Malkapur",
        "ancAge": 22,
        "gravida": "Primi",
        "previousDeliveryMode": "",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "1-Oct-2025",
        "addressOfDeliveredAborted": "Lavanya hospital",
        "modeOfDeliveryAborted": "Pvt-LSCS",
        "ashaName": "B.Rajitha",
        "ashaContactNo": "9989658170",
        "status": "ongoing"
    },
    {
        "id": 34,
        "subCentre": "Malkapur(SC)",
        "ancId": "P140200242053076",
        "ancName": "Soujanya",
        "ancContactNo": "8790504856",
        "lmp": "8-Jan-2025",
        "edd": "15/10/2025",
        "ancWo": "Mahesh",
        "village": "kondapur",
        "ancAge": 20,
        "gravida": "Primi",
        "previousDeliveryMode": "",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "10-Sep-2025",
        "addressOfDeliveredAborted": "GMH HNK",
        "modeOfDeliveryAborted": "Govt-LSCS",
        "ashaName": "M.Vijaya rani",
        "ashaContactNo": "8008876804",
        "status": "ongoing"
    },
    {
        "id": 35,
        "subCentre": "Nashkal(SC)",
        "ancId": "P140200292061010",
        "ancName": "Baske prasanna",
        "ancContactNo": "8801613340",
        "lmp": "9-Jan-2025",
        "edd": "16/10/2025",
        "ancWo": "Prashant",
        "village": "Nashkal",
        "ancAge": 22,
        "gravida": "Primi",
        "previousDeliveryMode": "",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "23-Sep-2025",
        "addressOfDeliveredAborted": "GMH Hanamakonda",
        "modeOfDeliveryAborted": "Govt-Normal",
        "ashaName": "ch joshana",
        "ashaContactNo": "7794054905",
        "status": "ongoing"
    },
    {
        "id": 36,
        "subCentre": "Pallagutta(SC)",
        "ancId": "P140200302050773",
        "ancName": "Bhukya Mamatha",
        "ancContactNo": "7971887560",
        "lmp": "21-Jan-2025",
        "edd": "28/10/2025",
        "ancWo": "Deshya",
        "village": "Deshaithanda",
        "ancAge": 22,
        "gravida": "Primi",
        "previousDeliveryMode": "",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "31-Oct-2025",
        "addressOfDeliveredAborted": "Gmh.hnk",
        "modeOfDeliveryAborted": "Govt-Normal",
        "ashaName": "B.Neela",
        "ashaContactNo": "8790336439",
        "status": "ongoing"
    },
    {
        "id": 37,
        "subCentre": "Pallagutta(SC)",
        "ancId": "P140200302023851",
        "ancName": "Singapuram Alankitha",
        "ancContactNo": "9347997814",
        "lmp": "27-Dec-2024",
        "edd": "03/10/2025",
        "ancWo": "Hari babu",
        "village": "Pallagutta",
        "ancAge": 25,
        "gravida": "Primi",
        "previousDeliveryMode": "",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "5-Oct-2025",
        "addressOfDeliveredAborted": "Gmh.Hnk",
        "modeOfDeliveryAborted": "Govt-LSCS",
        "ashaName": "D.Rajini",
        "ashaContactNo": "7702805475",
        "status": "ongoing"
    },
    {
        "id": 38,
        "subCentre": "Pallagutta(SC)",
        "ancId": "P140200302050738",
        "ancName": "Padya Pavani",
        "ancContactNo": "8978584003",
        "lmp": "29-Dec-2024",
        "edd": "05/10/2025",
        "ancWo": "Rajaram",
        "village": "Seethathanda",
        "ancAge": 20,
        "gravida": "Primi",
        "previousDeliveryMode": "",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "22-Sep-2025",
        "addressOfDeliveredAborted": "Pravite",
        "modeOfDeliveryAborted": "Pvt-LSCS",
        "ashaName": "M.Kalamma",
        "ashaContactNo": "8106395195",
        "status": "ongoing"
    },
    {
        "id": 39,
        "subCentre": "Pallagutta(SC)",
        "ancId": "P140200302048137",
        "ancName": "Bhukya Divya",
        "ancContactNo": "9059486853",
        "lmp": "1-Jan-2025",
        "edd": "08/10/2025",
        "ancWo": "Vijay kumar",
        "village": "Deshaithanda",
        "ancAge": 21,
        "gravida": "Primi",
        "previousDeliveryMode": "-",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "8-Sep-2025",
        "addressOfDeliveredAborted": "private",
        "modeOfDeliveryAborted": "Pvt-LSCS",
        "ashaName": "B.Neela",
        "ashaContactNo": "8790336439",
        "status": "ongoing"
    },
    {
        "id": 40,
        "subCentre": "Rajavaram(SC)",
        "ancId": "P140200272056876",
        "ancName": "Balugula swathi",
        "ancContactNo": "7093765700",
        "lmp": "13-Jan-2025",
        "edd": "20/10/2025",
        "ancWo": "Anil Kumar",
        "village": "Rajavaram",
        "ancAge": 26,
        "gravida": "Primi",
        "previousDeliveryMode": "Open Heart surgery",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "17-Oct-2025",
        "addressOfDeliveredAborted": "Rohini Haspital",
        "modeOfDeliveryAborted": "Pvt-LSCS",
        "ashaName": "A Padma",
        "ashaContactNo": "8106569127",
        "status": "ongoing"
    },
    {
        "id": 41,
        "subCentre": "Rajavaram(SC)",
        "ancId": "P140200272049277",
        "ancName": "Bhukya Akshaya",
        "ancContactNo": "9700030484",
        "lmp": "29-Dec-2024",
        "edd": "05/10/2025",
        "ancWo": "Jeevan",
        "village": "Keemathanda",
        "ancAge": 22,
        "gravida": "Primi",
        "previousDeliveryMode": "",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "1-Oct-2025",
        "addressOfDeliveredAborted": "Neelima Hospital Ghatkesar",
        "modeOfDeliveryAborted": "Pvt-LSCS",
        "ashaName": "G Neelima",
        "ashaContactNo": "9701696383",
        "status": "ongoing"
    },
    {
        "id": 42,
        "subCentre": "Sripathipally(SC)",
        "ancId": "P140200252035543",
        "ancName": "Ajjimera anusha",
        "ancContactNo": "9553378240",
        "lmp": "21-Jan-2025",
        "edd": "28/10/2025",
        "ancWo": "Samaiah",
        "village": "Lingampally",
        "ancAge": 20,
        "gravida": "Primi",
        "previousDeliveryMode": "",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "28-Mar-2025",
        "addressOfDeliveredAborted": "pvt Hnk",
        "modeOfDeliveryAborted": "Aborted",
        "ashaName": "B Rajitha",
        "ashaContactNo": "9553351138",
        "status": "aborted"
    },
    {
        "id": 43,
        "subCentre": "Sripathipally(SC)",
        "ancId": "P140200252025263",
        "ancName": "T Joshna",
        "ancContactNo": "9390044896",
        "lmp": "8-Jan-2025",
        "edd": "15/10/2025",
        "ancWo": "Suresh",
        "village": "Lingampally",
        "ancAge": 23,
        "gravida": "Primi",
        "previousDeliveryMode": "",
        "causeOfHighRisk": "",
        "birthPlan": "CHC Ghanpur Station",
        "dateOfDeliveryAborted": "13-Oct-2025",
        "addressOfDeliveredAborted": "Govt Husanabad",
        "modeOfDeliveryAborted": "OtherGovt-LSCS",
        "ashaName": "B Rajitha",
        "ashaContactNo": "9553351138",
        "status": "ongoing"
    }
]
